import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "ui Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
    
        <video
          src="/video.mp4"
          autoPlay
          muted
          loop
          className="video"
        />
        <div className="content">
        <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
